config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :movies do 
    resources :reviews, except: [:show, :index]
  end

  root 'movies#index'

  get '/api/movies/all' => 'movies#fetch_movies'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	#for seach elasticsearch
	searchkick word_start: [:title, :director]

	validates :title, presence: true, length: { minimum: 5, maximum: 50 }
	validates :description, presence: true
	validates :director, presence: true
	# validates :duration, presence: true, numericality: true
	validates :duration, presence: true, format: { with: /\A\d{1,2}:\d{1,2}\Z/, message: ":only time ralated expressions can be used !!" }
	
	belongs_to :user
	has_many :reviews

	has_attached_file :image, :styles => { small: "150x150>", :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def image_url
    	image.url
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  
  has_many :movies
  has_many :reviews

  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:login]
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#", :thumb2 => "50x50>" }
  
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  
  def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    if conditions[:username].nil?
	      where(conditions).first
	    else
	      where(username: conditions[:username]).first
	    end
	  end
	end
  
  
  # validates_attachment :avatar, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :cors_preflight
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = '*'    
  end

  def cors_preflight
    if request.method == :options
      render json: { status: "ok" }, status: :ok
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :destroy]
  # GET /movies
  # GET /movies.json
  
  def index
   if params[:query].present?
      
      @movies = Movie.paginate(:per_page => 3, :page => params[:page]).search(params[:query])
      @movies = nil if @movies.length < 1
    else
      @movies = Movie.paginate(:per_page => 3, :page => params[:page]).order("created_at DESC")
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id)
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating)
    end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #RESTFUL APIS
  def fetch_movies
    render json: Movie.all.to_json( :methods => [:image_url] ) , status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :duration, :director, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie

  # GET /reviews/new
  def new
    @review = current_user.reviews.build
  end

  # GET /reviews/1/edit
  def edit

  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.build(review_params)
    @review.movie_id = @movie.id
    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    respond_to do |format|
      format.html { redirect_to movie_url(@movie), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])

    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Movie Reviewer" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application"  %>
    <%= javascript_include_tag "jquery.raty.js", "data-turbolinks-track" => false %>
  </head>
  <body>
    <!-- (bg color start here) -->
    <!-- <div > -->
    <!-- (this div is for the backgourd color ) -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>"><i class="fa fa-film fa-lg"></i> Movie Reviewer</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><div><%= form_tag movies_path, class: "navbar-form form-inline", method: :get do text_field_tag :query, nil, class: 'form-control', placeholder: 'Quick Search...' end %></div></li>
            <li><%= link_to " Hello, #{current_user.username} !", edit_user_registration_path, class: "fa fa-user" %></li>
            <li><%= link_to " New Movie", new_movie_path, class: "fa fa-plus-square" %></li>
            <li><%= link_to " Sign out", destroy_user_session_path, method: :delete, class: "fa fa-sign-out" %></li>
          </ul>
          <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= form_tag movies_path, class: "navbar-form form-inline", method: :get do text_field_tag :query, nil, class: 'form-control', placeholder: "Quick Search..." end %>
            </li>
            <li><%= link_to " Sign up", new_user_registration_path, class: "fa fa-user-plus" %></li>
            <li><%= link_to " Sign in", new_user_session_path, class: "fa fa-sign-in" %></li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      
      </div> <!-- (bg wrapper color end) -->
    </body>
  </html>

app/views/movies/_form.html.erb
<%= form_for(@movie, html: { multipart: true }) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :duration %><br>
    <%= f.text_field :duration, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :director %><br>
    <%= f.text_field :director, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-info" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="reg-form" >
<h1 class="text-center">Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>
</div>

app/views/movies/index.html.erb
<div align="center">
  <% if @movies != nil %>
  <h1>List of Movies</h1>
  <% @movies.each do |movie| %>
  <div class="col-md-4">
    <div class="movie-prev">
      <h3 class="title"> <%= movie.title.truncate(20) %></h3>
      <p>
        <%= link_to image_tag(movie.image.url(:medium)), movie %>
        <div class="star-rating-show" data-number=<%= movie.reviews.average(:rating) %> ></div>
      </p>
      <p>
        <label>Run Time: </label>
        <%= movie.duration %>
      </p>
      <p>
        <label>Director: </label>
        <%= movie.director %>
      </p>
      <p><%= link_to (movie.reviews.length > 0) ? " Review  #{movie.reviews.length}" : " No Review", movie, :class => "form-control btn btn-info fa fa-comment-o" %></p>
      <% if current_user %>
      <p><%= link_to 'Edit', edit_movie_path(movie), :class => "form-control btn btn-info" %></p>
      <p><%= link_to 'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' }, :class => " form-control btn btn-warning" %></p>
      <% end %>
    </div>
  </div>
  <% end %>
  
  <!-- pagination -->
  <div class="paginate-wrapper">
    <%= will_paginate @movies, renderer: BootstrapPagination::Rails %>
  </div>
  <% else %>
  <h1> No Movies...</h1>
  <h2> search does not match any movie title or director...</h2>
  <%= link_to " Back to Movie Reviewer.....", movies_path, class: "fa fa-film fa-lg" %>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="reg-form" >
	<h1 class="text-center">New Movie</h1>

	<%= render 'form' %>

	<%= link_to 'Back', movies_path %>
</div>

app/views/movies/show.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-3">
			<%= image_tag @movie.image.url(:medium) %>
			<div class="star-rating-show" data-number=<%= @avg_review %> ></div>
			<p>
			  <strong>Title:</strong>
			  <%= @movie.title %>
			</p>
			<p>
			  <strong>Duration:</strong>
			  <%= @movie.duration %>
			</p>
			<p>
			  <strong>Director:</strong>
			  <%= @movie.director %>
			</p>
		</div>
		<div class="col-md-9">
			  <strong><label>Description:</label></strong> <br>
			  <p><%= @movie.description %></p>
		</div>
	</div>

	<% if @movie.reviews.length > 0 %>
		<h1><%= "Reviews  #{@movie.reviews.length}" %></h1>
		<div class="<%= @movie.reviews.length > 3 ? 'review-wrapper' : nil %>">
			<% @movie.reviews.order( :created_at ).reverse.each do |review| %>
			<div class="col-sm-12 well" >
				<div class="col-md-1">
					<%= image_tag review.user.avatar.url(:thumb2) %> 
				</div>
				<div class="col-sm-11">
					<h4><%= review.user.email %></h4>
					<div class="star-rating-show" data-number= <%= review.rating %> ></div>
					<br>
					<%= review.comment %> 
					<br> <br>
					<% if current_user == review.user  %>
						<%= link_to 'Delete', movie_review_path(@movie, review), method: :delete %> | 
						<%= link_to 'Edit', edit_movie_review_path(@movie,review) %> |
					<% end %>
					<%= time_ago_in_words(review.created_at) %>
				</div>
			</div>
			<% end %>
		</div>
	<%  else %>
		<h1 class="text-center"> No Reviews yet </h1>
		<h2 class="text-center">Be the first to make a review !!</h2>
	<% end %>

	<% if current_user %>
		<div class="col-md-12 form">
			<%= render partial: 'reviews/new' %>
			<%= link_to 'Edit', edit_movie_path(@movie) %> |
			<%= link_to 'Back', movies_path %>
		</div>
	<% end %>
</div> <!-- end of row -->

app/views/reviews/_form.html.erb
<%= form_for([@movie, @movie.reviews.new]) do |f| %>
  <div ><%= image_tag current_user.avatar.url(:thumb2) %></div>

  <div>
    <div id="star-rating-form" > </div>
  </div>

  
  <div class="form-group">
    <%= f.label 'What I think' %><br>
    <%= f.text_area :comment, :class =>"form-control"  %>
  </div>

  <div class="actions">
    <%= f.submit :class =>"btn btn-primary"  %>
  </div>
<% end %>

app/views/reviews/_new.html.erb
<h1 class="text-center" >My Review</h1>

<%= render 'reviews/form' %>

app/views/reviews/edit.html.erb
<div class="reg-form" >
  <h1>Editing Review</h1>
  <%= form_for([@movie, @review], html: { multipart: true }) do |f| %> 
    <div>
      <div id="star-rating-edit" data-number=<%= @review.rating %> > </div>
    </div>
  
    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<%- model_class = Review -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>